django_school/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^school/', include('school.urls', namespace='school')),
]

school/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^timetable/$', views.timetableView.as_view(), name='timetable'),
    url(r'^insights/(?P<year>[\d]+)/(?P<month>[\d]+)/$', views.insights, name='insights'),
    url(r'^insights/(?P<year>[\d]+)/(?P<month>[\d]+)/(?P<day>[\d]+)/$', views.insights, name='insights'),
]

school/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Base(models.Model):
    name = models.CharField('Name', max_length=45, blank=False, null=False, unique=True)
    doj = models.DateField('Date of Joining', blank=False, null=False)


    class Meta:
        abstract = True


class Chapter(models.Model):
    name = models.CharField('Name', max_length=45, blank=False, null=False, unique=True)

    def __str__(self):
        return "{}".format(self.name)


class Subject(models.Model):
    name = models.CharField('Name', max_length=45, blank=False, null=False, unique=True)
    chapters = models.ManyToManyField(
        Chapter, verbose_name='Chapters', null=False)
    total_duration = models.PositiveIntegerField('Total Duration', blank=False, null=False)
    per_class_duration = models.PositiveIntegerField(
        'Per Class Duration', blank=False, null=False,
        validators=[MaxValueValidator(120), MinValueValidator(30)])

    def __str__(self):
        return "{}".format(self.name)

class Teacher(Base):
    subjects = models.ManyToManyField(
        Subject, verbose_name='Subjects', null=False, related_name='subjects')
    salary = models.DecimalField(max_digits=10, decimal_places=2, blank=False, null=False)
    web_lecture_support = models.BooleanField(
        'Web Lecture Support', blank=True, null=False, default=False)

    def __str__(self):
        return "{}".format(self.name)


class Guardian(models.Model):
    name = models.CharField('Name', max_length=45, blank=False, null=False)
    phone = models.PositiveIntegerField(
        'Phone', blank=False, null=False, validators=[MaxValueValidator(10)])

    def __str__(self):
        return "{}".format(self.name)


    class Meta:
        unique_together = ('phone', 'name')


class Student(Base):
    roll_no = models.PositiveIntegerField('Roll No', blank=False, null=False)
    ranking = models.PositiveIntegerField('Ranking', blank=False, null=False)
    point_of_contact = models.ManyToManyField(
        Guardian, verbose_name='Point of Contact',
        null=False)

    def __str__(self):
        return "{}".format(self.name)


    class Meta:
        unique_together = ('roll_no', 'name')


class Classroom(models.Model):
    SHAPES = (
        (1, 'oval'),
        (2, 'rectangular'),
        (3, 'canopy'),
        (4, 'elevated'),
    )

    name = models.CharField(
        'Name', max_length=45, blank=False, null=False, unique=True)
    capacity = models.PositiveIntegerField('Capacity', blank=False, null=False)
    web_lecture_support = models.BooleanField(
        'Web Lecture Support', blank=True, null=False, default=False)
    shape = models.PositiveSmallIntegerField('Shape', choices=SHAPES, default=2)

    def __str__(self):
        return "{}".format(self.shape)


class TimeTable(models.Model):
    subject = models.ForeignKey(
        Subject, verbose_name='Subject', null=False, blank=False, related_name='subject')
    teacher = models.ForeignKey(
        Teacher, verbose_name='Teacher', null=False, blank=False, related_name='teacher')
    classroom = models.ForeignKey(
        Classroom, verbose_name='Classroom', null=False, blank=False, related_name='teacher')
    dt = models.DateField('Date of Joining', blank=False, null=False)

    class Meta:
        unique_together = ('dt', 'subject', 'teacher', 'classroom')

school/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django import forms
from django.utils import timezone
from school.models import *
from django.db.models import Q, Sum, Count


class timetableBuildForm(forms.Form):
    date = forms.DateField(
        widget=forms.TextInput(attrs={'class':'datepicker'}))
    month = forms.BooleanField(label='Show data for selected month', required=False)

    def clean(self):
        data = self.cleaned_data
        date = data.get('date')
        today = timezone.localtime(timezone.now())
        if date and date < today.date():
            raise forms.ValidationError('Timetable cannot be set for the past!')
        return data


class timetableView(FormView):
    template_name = 'timetable.html'
    form_class = timetableBuildForm

    def get(self, request):
        context = dict()
        context['form'] = self.form_class
        return render(request, self.template_name, context)


    def post(self, request):
        context = dict()
        form = self.form_class(request.POST)
        context['form'] = form

        if not form.is_valid():
            return render(request, self.template_name, context)

        data = form.cleaned_data
        dt = data['date']
        month = data['month']
        context['dt'] = dt
        context['month'] = month

        qs = Q(dt=dt)
        if month:
            qs = Q(dt__year=dt.year, dt__month=dt.month)

        #  dt, classroom, subjects , teachers .
        tt = TimeTable.objects.filter(qs).select_related(
            'classroom', 'subject', 'teacher').only(
                'dt',
                'classroom__name',
                'subject__name',
                'teacher__name',
                'classroom__web_lecture_support',
                'teacher__web_lecture_support').order_by('dt')
        if tt.exists():
            context['tt'] = list(tt)

        else:
            context['message'] = 'No data for {}'.format(dt)

        return render(request, self.template_name, context)

def insights(request, year, month, day=None):
    context = dict()
    template_name = 'insights.html'
    qs = Q(dt__year=year) & Q(dt__month=month)
    if day:
        qs &= Q(dt__day=day)

    basett = TimeTable.objects.filter(qs)
    # teachers earning more than 1 Lac per month and the sum of their salaries.
    lpagt12 = 1200000
    i1 = basett.select_related('teacher').filter(
        teacher__salary__gt=lpagt12).values_list(
            'teacher_id').distinct().aggregate(
                total_salary=Sum('teacher__salary'), count=Count('teacher_id'))

    # No of students, No of teachers, and total hours required for subjects that are taught by more than 1 teacher.
    i2 = Subject.objects.annotate(
        t=Count('subjects')).filter(t__gt=1).aggregate(
            total_hours=Sum('total_duration') / 60, tot_teachers_more_subs=Sum('t'))

    i1.update(i2)
    context.update(i1)

    context['dt'] = '{}-{}{}'.format(year, month, '-{}'.format(day) if day else '')

    return render(request, template_name, context)

templates/insights.html
<html>
    <head>
    </head>
    <body>
        <h2>Insights</h2>
        <p>
            - In timetable {{ dt }} there are <strong><i>{{ count }}</i></strong> teachers who are earning
            more than 1 lakhs per month and the sum of thir salaries is <strong><i>Rs.{{ total_salary }}</strong></i>
        </p>
        <p>- Total number of teachers who teach more than 1 subject: <strong><i>{{ tot_teachers_more_subs }} teachers</i></strong></p>
        <p>- Total hours for subjects that are taught by more than 1 teacher: <strong><i>{{ total_hours }} hours</i></strong></p>
    </body>
</html>

templates/timetable.html
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" type="text/css" media="all"/>
        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.5.min.js" type="text/javascript"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js" type="text/javascript"></script>
        <style>
            table, th, td {
              border: 1px solid black;
              border-collapse: collapse;
            }
            th, td {
              padding: 5px;
              text-align: left;
            }
        </style>
    </head>
    <body>
        <h1>Select date for which you wish to view Timetable</h1>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Show</button>
        </form>
        <h2>{{ message }}</h2>
        <br>
        {% if tt %}
            {% if month %}
                <a target="_blank" href="{% url 'school:insights' year=dt.year month=dt.month %}">Click here for Insights</a>
            {% else %}
                <a target="_blank" href="{% url 'school:insights' year=dt.year month=dt.month day=dt.day %}">Click here for Insights</a>
            {% endif %}
            <table style="width:100%">
                <caption>
                    <h3>Time Table</h3>
                </caption>
                <tr>
                    <th>Date</th>
                    <th>Classroom</th>
                    <th>Subject</th>
                    <th>Teacher</th>
                    <th>Web Lecture Available</th>
                </tr>
                {% for t in tt %}
                <tr>
                    <td>{{ t.dt }}</td>
                    <td>{{ t.classroom.name }}</td>
                    <td>{{ t.subject.name }}</td>
                    <td>{{ t.teacher.name }}</td>
                    {% if t.classroom.web_lecture_support and t.teacher.web_lecture_support %}
                        <td>Yes</td>
                    {% else %}
                        <td>No</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </table>
        {% endif %}
    </body>
    <script>
        $(function() {
            $( ".datepicker" ).datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "2019:2019",
            });
        });
    </script>
</html>